language: python

python:
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get install -y devscripts fakeroot debhelper

install:
  - pip install -r requirements-dev.txt
  - python setup.py install

script:
  - python setup.py test
  - find . -type f -name "*.py" | xargs flake8
  - mkdocs build -f docs/mkdocs.yml

after_success:
  - coverage run --source pygeometa setup.py test
  - coverage report -m
  - python3 setup.py sdist bdist_wheel --universal
  - sudo debuild -b -uc -us
